language: python
python:
    - 2.7
    - 3.4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - swig

env:
    - NUMPY_VERSION=1.11

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    
    # set the c++ and fortran compilers 
    - export CXX=g++-4.8 
    - export F90=gfortran-4.8

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    
    # base python setup
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py h5py pandas scipy pytables pyyaml astropy numba dask
    - pip install pytest pytest-cov pytest-pipeline coveralls
    
    # test optional HOD data sources
    - pip install halotools 
    
    # test optional Zeldovich data source
    - conda install --yes "swig>=3.0"
    - pip install --no-cache-dir classylss # ignore cache due to binaries

    # nbodykit and requirements
    - pip install --pre pfft-python kdcount mpsort pmesh sharedmem bigfile --no-deps
    - pip install --pre -r requirements.txt -e . # develop mode to track coverage of subproccess
    
script:
    - py.test nbodykit --cov=nbodykit --cov-report term-missing
    - bash check_tag.sh nbodykit/version.py

after_success:
    - coveralls
    
deploy:
    - provider: pypi
      distributions: sdist
      server: https://pypi.python.org/pypi
      user: "nickhand"
      password:
          secure: "SFknKu4DDcBYI6iQNhu4ihtqtQE15uKZ5KSU9qIdNRxLEZKp6urCWt67R3WM0wm6vj81fsSiCh9qvE0i8X3dZ1d2YOLm1CATeT+3zLIwY4GTmKRYv1l26uSmXiMye0LQOcRQu4o4qaitwHhMz3BtJzZ61JpelnSBnpT9MZfPKYdLS1Fgo5EL3WrxwMsztpnlI4WWCiZN+JJk0Ajo37PS7Oq1SjuKz0QNDMnraGo5XggBd3ZhlOolf/vW3q7jQlw6Pj9Xs9Aw+C66syMos/f3i7Hj1oO+F2Gv8qlvjDGvdBOjBJu/z39jJRXqKNfZr4uDT6cMP6qaWahnDQJeHFdH2Bc8XYvSVCOIqGT0qbVK7JoLefHIOJImRNyFzb0cV3dYWsYTwJZHz/RtQvMVZWEnB1Ev3Dvw3gxj7N8GMPigBa0dg7Pkey2cEaUFfvQcVk2gzRKWb3lAsfivzOacDW1sS9tAhyFIQdL8MFr/EvgN+IepktBnMVXGXacrVBgZHHTNcxCpnqgJtnMZzSXMfRkzc0oB1jE5opN06nKPvJJK0N+I5CLhvdJ3zn8Bn0Oxbg7BofVFnzPLAcYTsdVYdGSionsjaHjxEYf5sNGaAP0FoBulrwaCsXmMKIWLIpVsGMS2D7v2gZor1/zCBBvjwOf9O4yfRTSeDUo1wWFEWj3CqI4="
      on:
        tags   : true
        condition : $TRAVIS_PYTHON_VERSION = "2.7"
    
#notifications:
#  email: false
