# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for pyRSD.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create --name nbodykit-docs -f environment.yml

name: nbodykit-docs

channels:
- defaults
- bccp
- astropy
- conda-forge

dependencies:
- python=3.6
- numpy
- scipy
- astropy
- mpi4py
- runtests
- pmesh
- kdcount
- mpsort
- bigfile
- pandas
- dask>=0.14.2
- cachey
- sympy
- numexpr
- corrfunc
- mcfit
- classylss>=0.2
- h5py
- halotools
- fitsio
- numpydoc
- sphinx<1.6
- IPython
- pip
- pip:
  - nbsphinx
  - sphinx_bootstrap_theme
  - sphinx-issues
